### ISSUE TITLE
No longer takes effect on 5.45.3

### ISSUE THREAD

**Issue by andyburnsco** [JMAConsulting/biz.jmaconsulting.primaryexportdisable#2]
It should disable the `Export PRIMARY fields` radio option, but it no longer takes effect. Replicate by searching in advance search (does occur in other search screens). I tried both contact and event participants export ('Display results as'.)

My install upgraded from 5.35.2 (which is where it last worked) to 5.45.3. Can this be replicated by others?

![image](https://user-images.githubusercontent.com/18341942/154571992-0fe5782f-ce38-4075-8b57-2df35224d727.png)

**Comment by JoeMurray** [comment]
@monishdeb could you provide an estimate of work here and create a ticket in Clickup?

@andyburnsco I hope you're well. We're slammed with work and will have trouble fitting unpaid work in in the next while.

**Comment by andyburnsco** [comment]
Thanks @JoeMurray. We are open to funding (seeing we funded v1.0) if we know an estimate so appreciate you moving it forward. I've never been a fan of the primary export in it's current guise and this issue is currently open too https://lab.civicrm.org/dev/core/-/issues/2784

**Comment by andyburnsco** [comment]
@monishdeb do you have an estimate?

**Comment by twomice** [comment]
Looks like this was fixed in 8072e8768880df076dbfb5c6b5ca7582731adf02
